language: java
sudo: false # faster builds
cache:
  directories:
    - $HOME/.m2
after_success:
  - bash <(curl -s https://codecov.io/bash)
after_script:
  - python html2text.py target/site/surefire-report.html